### ISSUE TITLE
There is no "empty" expression

### ISSUE THREAD

**Issue by adamretter** [digital-preservation/csv-validator#11]
There is a "notEmpty" expression, but there is not an "empty" expression.

Whilst it is possible to express an empty column by using either - 

is("")

or even -

length(0)

this does not read very well in complex rules. It is better perhaps to be able to write something like -

if($other/starts("a"), is("a4"), empty)

as opposed to currently writing something like - 

if($other/starts("a"), is("a4"), is(""))

**Comment by spectramedix** [comment]
Hi, 
I am getting below exception message for empty and length(0) and is("") expressions.
Row Number: 0  Column Number: -1  Exception Message: metadata file has a header but no data and this has not been permitted

**Comment by adamretter** [comment]
@spectramedix please open a new issue and link to your csv file
