### ISSUE TITLE
Error handling for schemas that reference non-existent column

### ISSUE THREAD

**Issue by LauraDamianTNA** [digital-preservation/csv-validator#118]
CSV validator should fail with a meaningful error when a column name that does not exist is referenced in a schema.
Schema example:
           version 1.1
          @totalColumns 2
          foi_exemption_asserted:if($closure_type/is("closed_for"),not($date_last_modified))
          closure_type:

**Comment by DavidUnderdown** [comment]
There's more discussion on #128 which is essentially a duplicate so will close this one
