### ISSUE TITLE
Integritycheck fails on paths including minus signs

### ISSUE THREAD

**Issue by seamang** [digital-preservation/csv-validator#129]
Integritycheck breaks paths at minus signs, and then fails to find the resource at that path. 

For example, given a folder containing a file at:

/mnt/test/RW_32/content/IM_TNA_102013_1015.fluencycontent-schoolwebsite.netdna-ssl.com/IM_TNA_102013_1015.fluencycontent-schoolwebsite.netdna-ssl.com-20151118170135-00000.arc.gz

Integritycheck fails on both the directory and the file:

Error:   integrityCheck fails for line: 14006, column: identifier, Cannot find the folder /mnt/test/RW_32/content/IM_TNA_102013_1015.fluencycontent with substitution paths (file:///T:WORK/RW_32,/mnt/test/RW_32)
Error:   integrityCheck fails for line: 14007, column: identifier, Cannot find the folder /mnt/test/RW_32/content/IM_TNA_102013_1015.fluencycontent-schoolwebsite.netdna-ssl.com/IM_TNA_102013_1015.fluencycontent with substitution paths (file:///T:WORK/RW_32,/mnt/test/RW_32)

In addition the second error message references the folder as the problem, where the folder name is actually correct, and it is the filename which has been truncated.

**Comment by rhubner** [comment]
Limited fix. We pick up last content folder in whole path.
