### ISSUE TITLE
Separator being detected in values encased in quotation marks; quoted directive being used

### ISSUE THREAD

**Issue by RaccoTaco** [digital-preservation/csv-validator#147]
For the CSV file, a separator of ',' is being used. However, for some values within a column, a separator can be found (ie, Name of product: "Cheese, Low Fat") . Can the separator be expanded into using regex? Or is there another way I can go about this without changing the separator value?

**Comment by DavidUnderdown** [comment]
You should just quote-wrap the field if it contains separator characters, ie your CSV file would have "Cheese, Low Fat" (including the quote marks) in the name_of_product field eg:

quantity,name_of_product,unit_price
5,"Cheese, Low Fat",2.50
1,"Cheese, stilton",3.70
3,"Milk, semi-skimmed",0.50
5,Pork pie,4.00

**Comment by RaccoTaco** [comment]
All values are encased in quotation marks, and those values are separated by a comma. However, when running through the validation, I get errors back.

**Comment by DavidUnderdown** [comment]
Can you give an actual example of the csv and schema please? it's more likely to be something other than the separators in that case.

**Comment by RaccoTaco** [comment]
Oh, sorry about that. I just double checked in the file and noticed an empty line throughout the 90k+ lines.  Again, so sorry about that.
