### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by RaccoTaco** [digital-preservation/csv-validator#148]
Sorry to bother again; I found one more issue within the file. Some of the products contain special characters, like "Piñata" -- and from that, I get a "Invalid UTF-8 sequence" error. Is there any way that those characters can be passed in without error?

**Comment by adamretter** [comment]
@RaccoTaco There is nothing about "Piñata" that would mean that it could not be encoded in UTF-8. I suspect that your input file is not correctly encoded with the UTF-8 charset. You can use this tool to check https://github.com/digital-preservation/utf8-validator
