### ISSUE TITLE
Error on range validation when value can be empty

### ISSUE THREAD

**Issue by valnz** [digital-preservation/csv-validator#162]
Hi, when validation tool try to check if value is in a range, I think it should not throw error if value is empty (i.e. = ''). Can this logic be somehow overwritten or do you think it is a bug?

**Comment by DavidUnderdown** [comment]
If you want empty values to be allowed as well, use the @optional directive.  range means there must be a numeric value in the stated range.

**Comment by valnz** [comment]
Thanks David, thanks for your answer, it really helped and it worked. I think it could be very helpful if you add information about it under Not Empty Expression. It seems like if you specify a range, you expect value to be not empty, so I was expecting to find this information under this section.

**Comment by DavidUnderdown** [comment]
They're fundamentally different things, notEmpty means there must be something (anything) in this field, but we don't care what.  Otherwise as soon as you specify a rule on a field the data must precisely match the test given (unless you supply the optional directive, which means if there is some data in this field in must match the rule)

**Comment by valnz** [comment]
Hi David, but when I don't specify notEmpty, I assume, that value can be empty in any other case, Anyway, maybe it is just my understanding, but I think it is confusing.

**Comment by valnz** [comment]
Hi David, but you don't read all document, when creating these schemas, I think more clarity needs to be added in places where people trying to find information about a concrete column definition rule, like where notEmpty or at least where range is. You already have a use case, where person couldn't find about it easily, isn't it enough?

**Comment by DavidUnderdown** [comment]
The range definition starts "checks that the value of the column is a number", fundamentally a blank is not a number.  However, maybe the easiest thing to do is just expand the range of examples there to give one using the optional directive.
