### ISSUE TITLE
Change end of line character

### ISSUE THREAD

**Issue by valnz** [digital-preservation/csv-validator#163]
Hi, I couldn't find how to specify different "new line" character. Can it be added or maybe I miss something?
Thanks heaps for answer in advance.

**Comment by DavidUnderdown** [comment]
There isn't an option for that I'm afraid.  However, both Windows and Linux line endings will work I think, and it's likely the underlying CSV library would understand other common endings too, have you tried it?

**Comment by valnz** [comment]
Hi David, some files that I am trying to validate originate from old Sybase system, and they have special end of line character set, I will try it tomorrow at work, and will let you know if it worked. Thank you for a quick response.

**Comment by DavidUnderdown** [comment]
OK.  Your best bet in the short-term (if it doesn't work) may be to simply find-and-replace the line ending with a standard one as we're short of developers at the moment so it's unlikely we'd be able to prioritise any sort of enhancement request at the moment.

**Comment by adamretter** [comment]
@valnz CSV Validator is based on OpenCSV, we also have a PR waiting to be merged which switched it to uniVocity. Unfortunately neither the OpenCSV or uniVocity parsers as far as I can tell support anything other than Windows (CRLF), Unix (LF), and Mac before OSX (CR).

Out of interest what is the line ending in your Sybase system?

I think as @DavidUnderdown suggested, your best bet right now is to do a conversion of the text format of the CSV files first to move to a more modern line ending, and then use the CSV Validator on the converted files.

**Comment by adamretter** [comment]
@DavidUnderdown as our underlying choice of parsers does not support the line endings requested by @valnz, I suggest we close this ticket as "wonfix".

**Comment by valnz** [comment]
Hi, thanks guys for comments and explanation. I was not able to test it today due to many interruptions at work. Will be testing it tomorrow.

**Comment by valnz** [comment]
Hi guys, Sybase was giving us files with 0x0A as a new line, and it is a new line in ASCII, which magically worked. I couldn't get the file itself that why was not able to test it. And by the look of the chars in requirements on a meeting, thought it must be some special Sybase "new line". But it appeared that it is just a different encoding. Thanks for your support, probably issue can be closed :)
