### ISSUE TITLE
UTF 8 errors

### ISSUE THREAD

**Issue by WesAnderson-NJ** [digital-preservation/csv-validator#165]
I am getting UTF 8 errors like
1) Invalid UTF -8 sequence byte  of  byte multibyte sequence
2) Invalid single byte UTF-8 character 

Any directive or declare statement to avoid such errors ?

**Comment by DavidUnderdown** [comment]
Is your data expected to be UTF-8?

You can control UTF-8 validation via the settings pane if you're using the GUI, see http://digital-preservation.github.io/csv-validator/#toc7 (you can choose windows 1252 instead, or disable altogether), or via command line options http://digital-preservation.github.io/csv-validator/#toc11

**Comment by spectramedix** [comment]
I am using csv-validator-java-api.

**Comment by spectramedix** [comment]
I am using csv-validator-java-api, how can i pass the argument "--disable-utf8-validation" in command line.

**Comment by DavidUnderdown** [comment]
Hopefully one of the developers will be able to explain that

**Comment by WesAnderson-NJ** [comment]
Thanks for adding this feature, how can i enable/disable this UTF-8 validation ?
