### ISSUE TITLE
Catch SingleSpace String

### ISSUE THREAD

**Issue by WesAnderson-NJ** [digital-preservation/csv-validator#166]
RegexRule: `notEmpty` is not working for the strings `" "` with single or more space strings.

My rules are: `regex("?![\s]") ; not("\\s") ; not("[\s]") ; not(" ")`.

Please suggest me a rule for this scenario

**Comment by DavidUnderdown** [comment]
This feels like a bug, it's probably the underlying CSV library dropping spaces.

**Comment by DavidUnderdown** [comment]
Sorry this is not a bug, notEmpty means there is nothing at all in the field, ie an empty string.

If you want to allow some amount of white space, but nothing else, regex("^\s*$") would be minimal I think.

**Comment by DavidUnderdown** [comment]
Your example file and schema validate OK in the GUI, so it's possible there's a bug in the API. Are you seeing any other errors in the console?

**Comment by spectramedix** [comment]
No other errors

**Comment by LauraDamianTNA** [comment]
Hi,

I tried your file and schema with the csv-validator-java api and I got no errors.
Here is how i did it:
https://gist.github.com/LauraDamianTNA/14adfc3c1e1bf0b91ec312db59d72507

**Comment by spectramedix** [comment]
Hi Laura,
Thanks for the reply, even i am able to run the file but unable to catch the string which has single spaces 
For Ex: if my rule is:- notEmpty and regex("^\s*$") and the string is " "(which has single space)
It has to throw an error - but it is not(though its not empty but has to catch that single space character)

Please check this and let me know a better rule.

**Comment by DavidUnderdown** [comment]
Sorry, I think we've been slightly at cross purposes, you want to fail if it's not empty, but contains only whitespace?

In that case changing the regex part to regex("^\S*$") should work, ie whatever's in the notEmpty content must be something other than purely whitespace characters.

**Comment by spectramedix** [comment]
David, you are partially correct- case1: I want to fail when the cell has -  " "
But, the above regex rule is failing even for this case2- when cell has -  "ab cd".
I want to fail only case1.

**Comment by adamretter** [comment]
@WesAnderson-NJ What you really are asking for is help to write a Java regular expression that matches for your use-cases.

I think you might this article helpful - https://stackoverflow.com/questions/5599934/regular-expression-that-allows-spaces-in-a-string-but-not-only-blank-spaces

You can also try out your regular expressions here - https://regexper.com/
