### ISSUE TITLE
Unable to deploy the project inNetbeans

### ISSUE THREAD

**Issue by WesAnderson-NJ** [digital-preservation/csv-validator#167]
I am getting the following exception when i am trying to deploy the whole project in netbeans.

Failed to execute goal on project csv-validator-ui: Could not resolve dependencies for project uk.gov.nationalarchives:csv-validator-ui:jar:1.2-RC3-SNAPSHOT: The following artifacts could not be resolved: uk.gov.nationalarchives:csv-validator-cmd:jar:1.2-RC3-SNAPSHOT, uk.gov.nationalarchives:csv-validator-core:jar:1.2-RC3-SNAPSHOT: Could not find artifact uk.gov.nationalarchives:csv-validator-cmd:jar:1.2-RC3-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by adamretter** [comment]
@WesAnderson-NJ I would try running `mvn clean install` from the command prompt before opening the project in NetBeans.
