### ISSUE TITLE
upper/lower expressions

### ISSUE THREAD

**Issue by adamretter** [digital-preservation/csv-validator#17]
It would be nice to have expressions that assert that text in a field is either all upper-case or all lower-case. e.g. 

field1: upper
field2: lower

**Comment by DavidUnderdown** [comment]
upperCase and lowerCase introduced in Pull Request 91

**Comment by DavidUnderdown** [comment]
See above reference to Pull Request #91

**Comment by DavidUnderdown** [comment]
See also #87
