### ISSUE TITLE
UTF-16 makes the validator unhappy

### ISSUE THREAD

**Issue by afranke** [digital-preservation/csv-validator#177]
The sample file I test my schema against is UTF-16 encoded. When I try to validate it, it breaks because the file starts with a header that gets parsed as part of the name of the first column, and that obviously doesn’t match the name in the schema.

```
$ ./csv-validator/csv-validator-cmd-1.1.5/bin/validate sample.tsv db-import.csvs
Error:   [UTF-8 Error][@2] Invalid UTF-8 sequence, byte 2 of 4 byte multibyte sequence.
Error:   [UTF-8 Error][@3] Invalid UTF-8 sequence, byte 3 of 4 byte multibyte sequence.
Error:   [UTF-8 Error][@4] Invalid UTF-8 sequence, byte 4 of 4 byte multibyte sequence.
Error:   Metadata header, cannot find the column headers - provider_object_id, ��provider_object_id - .  (Case sensitive)
FAIL
```

**Comment by DavidUnderdown** [comment]
UTF-16 is not currently supported I'm afraid.  Only UTF-8 (without BOM) or windows-1252.  One problem is that with plain text formats such as csv there's no way to declare an encoding within the file.  I don't know how much effort it would be for anyone to add further encodings into the validation mechanism (and we're still rather shorthanded ourselves).

**Comment by afranke** [comment]
Wait a minute… I just found `-x` while looking for something else in `--help`. I tried it with `-x utf-16` and it seemed to work. Are you still saying it isn’t supported, or is it just autodiscovery of UTF-16 that is not supported? I can live with having to specify the charset on the command line!

**Comment by adamretter** [comment]
Multiple encodings should be supported. You can select them using `-x` for the CSV file and `-y` for the CSV Schema file.
