### ISSUE TITLE
gradle: dependency com.gilt:gfc-semver_2.11:0.1.0 can't be resolved

### ISSUE THREAD

**Issue by beoChr** [digital-preservation/csv-validator#184]
I have some issues with the gfc-semver dependency. Using gradle and intelliJ 2019.1.3.

Seams like the repository `http://dl.bintray.com/giltgroupe/maven` does response with an 500 error.

Yesterday I added the csv-validator the my project. At first the dependency couldn't be resolved, but after 5 minutes of tinkering around, it suddenly worked.

Today I ran a `gradle build`, now gradle again can't load the dependency anymore. 

I added the repo manually, and got an error 500.
![mvn](https://user-images.githubusercontent.com/51781254/59419628-963d7b80-8dcb-11e9-95a3-8b73e3512cce.png).

Any suggestions?

**Comment by adamretter** [comment]
The BinTray repository seems to be functioning fine from here right now. BinTray is usually very stable, perhaps they were just having a "blip", let us know if you have continued problems with it...

**Comment by beoChr** [comment]
Thanks for the quick answer.

I just updated gradle, but it didn't help.

Seams to be another problem. I can visit `https://dl.bintray.com/giltgroupe/maven/` in the browser, but when I do a `https://dl.bintray.com/giltgroupe/maven/` I get a "Host not found" exception. Same for `https://bintray.com`

**Comment by beoChr** [comment]
`curl https://dl.bintray.com/giltgroupe/maven` gives my:

`<html><body>Moved to <a href="http://dl.bintray.com:80/v1/content/giltgroupe/maven/">http://dl.bintray.com:80/v1/content/giltgroupe/maven/</a></body></html>`

**Comment by beoChr** [comment]
I could fix it. The problem seams to be the name of the dependency.

I added it with 

`
dependencies {
         compile (
                 //some other dependencies,
                 ''com.gilt:gfc-semver_2.11:0.1.0''
         )
`

Somewhere I found an error stating "can't resolve gfc-semver_". So I guess the number is interpreted as version, which is behind the last ":".

So I changed it to 

`
dependencies {
         compile (
                 //some other dependencies
         )
        compile group: 'com.gilt', name: 'gfc-semver_2.11', version: '0.1.0'
`

Now it works.
