### ISSUE TITLE
any expression

### ISSUE THREAD

**Issue by adamretter** [digital-preservation/csv-validator#19]
It would be easier if we had an 'any' expression rather than combining several string options with 'or'.

e.g. This - 

is("a") or is("b") or is("c")

Could be replaced with - 

any("a", "b", "c")

This is arguably more readable, especially when many 'or' expressions are used.

**Comment by DavidUnderdown** [comment]
See references above, implemented in development, will close on release.

See also [Issue 5](https://github.com/digital-preservation/csv-schema/issues/5) of the CSV Schema repository.

**Comment by DavidUnderdown** [comment]
In 1.1 release, commit 104ee5e
