### ISSUE TITLE
Does not work in gradle build

### ISSUE THREAD

**Issue by philip-energetiq** [digital-preservation/csv-validator#232]
"If you wish to use the CSV Validator from your own Java project, we provide a native Java API, the dependency details are:"

If I add to my gradle build and try to build it doesn't work.

I tried many things, can only get it to work if I import all dependent jars.

**Comment by adamretter** [comment]
>  it doesn't work.

What doesn't work?

> I tried many things

What did you try?

**Comment by PhilAndrew** [comment]
What doesn't work is if I add the dependency as you described as a gradle dependency. I'll try to make a failure case tomorrow then.

This works if I add all the dependant jars.

https://github.com/PhilAndrew/csv-validator

**Comment by adamretter** [comment]
@PhilAndrew Can you provide examples of what works and what doesn't work.

We have used and tested the csv-validator-java-api in other projects.

As you can see here: https://github.com/digital-preservation/csv-validator/blob/master/csv-validator-java-api/pom.xml#L134
The `csv-validator-java-api` has a dependency on `cav-validator-core`, and so all you need is a single dependency on `csv-validator-api`.

**Comment by DavidUnderdown** [comment]
No response to our clarifying question
