### ISSUE TITLE
dependency convergence warnings

### ISSUE THREAD

**Issue by gurpiarbassi** [digital-preservation/csv-validator#235]
I am using the enforcer plugin and it detects a lot of dependency convergence issue with the underlying scala libraries.

I am using csv-validator-java-api Version 1.1 and using the dependencyConvergence rule in the maven enforcer plugin.

**Comment by adamretter** [comment]
@gurpiarbassi can you provide some more detail on the errors please?

**Comment by gurpiarbassi** [comment]
Here are the issues:
`
[WARNING]
Dependency convergence error for org.scala-lang.modules:scala-parser-combinators_2.11:1.0.2 paths to dependency are:
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-org.scalaz:scalaz-core_2.11:7.1.1
      +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.2
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-com.github.scala-incubator.io:scala-io-file_2.11:0.4.3-1
      +-com.github.scala-incubator.io:scala-io-core_2.11:0.4.3-1
        +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.1
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-com.github.scala-incubator.io:scala-io-file_2.11:0.4.3-1
      +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.1
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.3

[WARNING]
Dependency convergence error for org.scala-lang:scala-library:2.11.6 paths to dependency are:
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-org.scala-lang:scala-library:2.11.6
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-org.scalaz:scalaz-core_2.11:7.1.1
      +-org.scala-lang:scala-library:2.11.5
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-org.scalaz:scalaz-core_2.11:7.1.1
      +-org.scala-lang.modules:scala-parser-combinators_2.11:1.0.2
        +-org.scala-lang:scala-library:2.11.1
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-org.scalaz:scalaz-core_2.11:7.1.1
      +-org.scala-lang.modules:scala-xml_2.11:1.0.2
        +-org.scala-lang:scala-library:2.11.1
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-com.github.scala-incubator.io:scala-io-file_2.11:0.4.3-1
      +-org.scala-lang:scala-library:2.11.0
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-com.github.scala-incubator.io:scala-io-file_2.11:0.4.3-1
      +-com.github.scala-incubator.io:scala-io-core_2.11:0.4.3-1
        +-org.scala-lang:scala-library:2.11.0
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.scala-lang:scala-library:2.11.6
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.scalaz.stream:scalaz-stream_2.11:0.6a
        +-org.scala-lang:scala-library:2.11.4
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.typelevel:scodec-bits_2.11:1.0.4
        +-org.scala-lang:scala-library:2.11.0
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.typelevel:scodec-bits_2.11:1.0.4
        +-org.scala-lang:scala-reflect:2.11.0
          +-org.scala-lang:scala-library:2.11.0
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-com.gilt:gfc-semver_2.11:0.1.0
        +-org.scala-lang:scala-library:2.11.6

[WARNING]
Dependency convergence error for org.scalaz:scalaz-core_2.11:7.1.1 paths to dependency are:
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-org.scalaz:scalaz-core_2.11:7.1.1
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.scalaz:scalaz-core_2.11:7.1.1
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.scalaz.stream:scalaz-stream_2.11:0.6a
        +-org.scalaz:scalaz-core_2.11:7.1.0

[WARNING]
Dependency convergence error for commons-io:commons-io:1.3.2 paths to dependency are:
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-commons-io:commons-io:1.3.2
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-commons-io:commons-io:2.6

[WARNING]
Dependency convergence error for com.madgag:scala-arm_2.11:1.3.3 paths to dependency are:
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-com.github.scala-incubator.io:scala-io-file_2.11:0.4.3-1
      +-com.github.scala-incubator.io:scala-io-core_2.11:0.4.3-1
        +-com.madgag:scala-arm_2.11:1.3.3
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-com.madgag:scala-arm_2.11:1.3.4

[WARNING]
Dependency convergence error for org.scalaz:scalaz-concurrent_2.11:7.1.0 paths to dependency are:
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.scalaz.stream:scalaz-stream_2.11:0.6a
        +-org.scalaz:scalaz-concurrent_2.11:7.1.0
and
+-com.mycompany.xda:xda-csv-validator:1.0-SNAPSHOT
  +-uk.gov.nationalarchives:csv-validator-java-api:1.1
    +-uk.gov.nationalarchives:csv-validator-core:1.1
      +-org.scalaz:scalaz-concurrent_2.11:7.1.1
`

**Comment by adamretter** [comment]
Unless I have missed something in your issue, this seems OK to me...

These are warnings rather than errors. In my opinion this is how Maven should work. It would be kinda crazy if I had to manually exclude all lesser versions of transient dependencies by hand.

**Comment by gurpiarbassi** [comment]
I've had issues in the past where more than 1 version of a library was included and you didn't know which one it was going to use at runtime. That led to a bug being discovered. These type of bugs can be hard to find. The fix was to ensure that specific version got excluded.

Other library maintainers e.g. Pivotal are taking these issues on board and ensuring conflicting versions are not included in their binaries.

These are the kind of issues Maven has tried to help with by providing a enforcer plugin: http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html

**Comment by adamretter** [comment]
> ensuring conflicting versions are not included in their binaries.

Having conflicting versions in our binaries would indeed be an issue. I don't think we have this problem though unless you have found otherwise?

**Comment by gurpiarbassi** [comment]
I have not found an issue so far. I just happen to be using the enforcer plugin as a best practice and it picked up on these warnings.

I have worked around this for now by pinning a single version of the transitive dependencies in conflict and excluding all the others.

**Comment by adamretter** [comment]
@gurpiarbassi Okay great. I think we are unlikely to address these warnings unless they become a bigger issue. Thanks for your feedback.
