### ISSUE TITLE
Network locations

### ISSUE THREAD

**Issue by eilandnl** [digital-preservation/csv-validator#243]
It doesnt seem to work when the path is a network location

i tried many difrrent variantion but when my input is
 
file:////server//Groups$//t1.csv
file://server/Groups$/t1.csv
////server//Groups$//t1.csv
//server/Groups$/t1.csv
////ip//Groups$//t1.csv
//ip/Groups$/t1.csv

none of them seem to work

**Comment by adamretter** [comment]
@eilandnl You are going to need to provide a lot more information...

1. What operating system are you using?
2. What network file system are you using?
3. What was the exact command that you ran?

**Comment by eilandnl** [comment]
1. Windows 10 
2. SMB
3. D:\Config\csv-validator-cmd-1.1.5\bin\validate.bat "\\PWFS\z$\x\y/csvschematest.csv" "\\PWFS\z$\x\y/csvschematest.csv.csvs" --disable-utf8-validation --fail-fast 1

Results in 
Error: Cannot access CSV file: **C:\PWFS**\z$\x\y\csvschematest.csvError: Cannot access CSV Schema file: C:\PWFS\z$\x\y\csvschematest.csv.csvsTry --help for more information.

**Comment by adamretter** [comment]
Hi @eilandnl I think you are trying to use UNC paths. Most applications won't work directly with these, instead you should mount the filesystem as a network drive.

Rehardless, I think your UNC path should start with a `\\` instead of `\`

**Comment by eilandnl** [comment]
Making a symbolic link solved the problem 
mklink /D "c:\x\y" "\\PWFS\Groups$\x\y"
