### ISSUE TITLE
Cant Run downloaded csv-validator-ui-1.2-RC2

### ISSUE THREAD

**Issue by n3ffv1** [digital-preservation/csv-validator#246]
I created a sample CSV / CSVs but once i clicked validate, this is being displayed in CMD. 

> java.lang.NoClassDefFoundError: java/nio/charset/StandardCharsets
>         at uk.gov.nationalarchives.csv.validator.package$.<init>(package.scala:22)
>         at uk.gov.nationalarchives.csv.validator.package$.<clinit>(package.scala)
>         at uk.gov.nationalarchives.csv.validator.schema.v1_0.SchemaValidator.validate(SchemaValidator.scala:26)
>         at uk.gov.nationalarchives.csv.validator.schema.v1_0.SchemaValidator$.apply(SchemaValidator.scala:276)
>         at uk.gov.nationalarchives.csv.validator.schema.SchemaValidator$.validate(SchemaValidator.scala:30)
>         at uk.gov.nationalarchives.csv.validator.schema.SchemaParser$class.parseAndValidate(SchemaParser.scala:126)
>         at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.parseAndValidate(CsvValidator.scala:32)
>         at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anonfun$parseSchema$1.apply(CsvValidator.scala:74)
>         at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anonfun$parseSchema$1.apply(CsvValidator.scala:73)
>         at uk.gov.nationalarchives.csv.validator.MetaDataValidator$$anonfun$14.apply(MetaDataValidator.scala:259)
>         at uk.gov.nationalarchives.csv.validator.MetaDataValidator$$anonfun$14.apply(MetaDataValidator.scala:258)
>         at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:86)
>         at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
>         at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
>         at scala.util.control.Exception$Catch.apply(Exception.scala:103)
>         at scala.util.control.Exception$Catch.either(Exception.scala:125)
>         at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:86)
>         at resource.DeferredExtractableManagedResource.either(AbstractManagedResource.scala:29)
>         at uk.gov.nationalarchives.csv.validator.MetaDataValidator$class.withReader(MetaDataValidator.scala:260)
>         at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.withReader(CsvValidator.scala:32)
>         at uk.gov.nationalarchives.csv.validator.api.CsvValidator$class.parseSchema(CsvValidator.scala:72)
>         at uk.gov.nationalarchives.csv.validator.api.CsvValidator$$anon$2.parseSchema(CsvValidator.scala:32)
>         at uk.gov.nationalarchives.csv.validator.cmd.CsvValidatorCmdApp$.validate(CsvValidatorCmdApp.scala:132)
>         at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$.uk$gov$nationalarchives$csv$validator$ui$CsvValidatorUi$$validate(CsvValidatorUi.scala:130)
>         at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$ContentPanel$$anonfun$5$$anonfun$apply$mcV$sp$5.apply(CsvValidatorUi.scala:285)
>         at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$ContentPanel$$anonfun$5$$anonfun$apply$mcV$sp$5.apply(CsvValidatorUi.scala:285)
>         at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply$mcV$sp(CsvValidatorUi.scala:114)
>         at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply(CsvValidatorUi.scala:114)
>         at uk.gov.nationalarchives.csv.validator.ui.CsvValidatorUi$$anonfun$2.apply(CsvValidatorUi.scala:114)
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
>         at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> Caused by: java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 36 more

**Comment by adamretter** [comment]
Which version of Java are you trying to run it with?

**Comment by DavidUnderdown** [comment]
No response to our clarifying question, closing
