### ISSUE TITLE
noext recorded as noExt in schema language but noext in code

### ISSUE THREAD

**Issue by adesousa576** [digital-preservation/csv-validator#269]
Hello,

I was trying to use noExt as in the schema language documentation and was getting errors and then a code check showed it's actually in there as noext. Could either the schema language be updated to reflect it's all lowercase or the code updated to match the schema language documentation please (which would be more in line with the other rules but it's up to you what's best!)

Many thanks
Anna

**Comment by DavidUnderdown** [comment]
noExt is more consistent with other rules, should be changed in CSV Validator to match definition
