### ISSUE TITLE
Error when running the latest revision in master

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/csv-validator#271]
CSV Validator latest revision fails with the error 

`Found class scodec.bits.ByteVector but interface was expected` for line: 3, column: checksum`

The latest binary on maven-central (https://search.maven.org/remotecontent?filepath=uk/gov/nationalarchives/csv-validator-ui/1.1.5/csv-validator-ui-1.1.5-application.zip) works without any problems.

When looking through the history of master, I could not see a revision corresponding to v1.1.5

**Comment by DavidUnderdown** [comment]
There's a release tagged for 1.1.5 https://github.com/digital-preservation/csv-validator/releases/tag/1.1.5 - it was quite a while ago as there hasn't been any active development on the validator, I think the only things that have been merged in are dependency updates. Maybe one of those has broken something?

**Comment by DavidUnderdown** [comment]
@sparkhi is this still an issue or should we close?
