### ISSUE TITLE
gfc-semver dependency not in Maven central

### ISSUE THREAD

**Issue by marceloverdijk** [digital-preservation/csv-validator#284]
Core depends on

```
        <dependency>
            <groupId>com.gilt</groupId>
            <artifactId>gfc-semver_${scala.compat.version}</artifactId>
            <version>0.1.0</version>
        </dependency>
```

which is not available in Maven Central:

![image](https://user-images.githubusercontent.com/197004/116607019-c778b380-a931-11eb-852f-c12b730c04cb.png)

In my Gradle build I had to exclude the transitive dependency and include it myself like:

```
    implementation("uk.gov.nationalarchives:csv-validator-java-api:1.1.4") {
        exclude group: "com.gilt", module: "gfc-semver_2.11"
    }
    implementation("com.gilt:gfc-semver_2.11:0.0.5")
```

Note it uses `0.0.5` but it seems to work.

Note II: It seems there is also a `org.gfccollective:gfc-semver` artifact on Maven Central.

**Comment by adamretter** [comment]
Fixed in f7c3878a4fee2c7e3cb6ecc7e0ac28e630d66ff2
