### ISSUE TITLE
How can I manage CSV files whose header column contain whitespace

### ISSUE THREAD

**Issue by fconil** [digital-preservation/csv-validator#305]
Hi,
I found the specification and the tool very interesting but I did not succeed to define a schema for our CSV files : the column names in the header contains whitespace.
```
"Trial ID","Trial Description","Type of trial"
```
Is there a way to use this case which seems usual ?

I tried the following schemas without success
```
"Trial ID": unique
"Trial Description":
"Type of trial": any("one", "two", "three")
------
Trial ID: unique
Trial Description:
Type of trial: any("one", "two", "three")
------
# Also tried beginning with zero
1: unique
2:
3: any("one", "two", "three")
```
Regards

**Comment by DavidUnderdown** [comment]
Your first option there should work as described in http://digital-preservation.github.io/csv-schema/csv-schema-1.1.html#column-identifiers. Do you have the exact error produced?

**Comment by fconil** [comment]
Hi,
I make some new trials and I made a mistake : column names headers can contain whitespace.
I guess I have been mistaken because of the error message I got due to the comments in the Prolog (#306 : `Invalid column definition`).
Sorry I am closing the issue
