### ISSUE TITLE
'save' button for saving reports take user to 'open' box

### ISSUE THREAD

**Issue by clairedriver** [digital-preservation/csv-validator#331]
When users (government departments) have tried to validate and want to save the report to send to TNA for advice. Press 'save' but they are taken to a page to open a new file rather than saving the existing one. There is a work around but very confusing for users and difficult for TNA to advise without the report, just a screen shot. 

![csv_val_Issue](https://user-images.githubusercontent.com/57437870/153608294-82ce42a1-b0c2-4507-aaf7-24473a3c1bfe.png)

**Comment by DavidUnderdown** [comment]
Thanks Claire

This should be quite straightforward I would think and we should have someone working on CSV Validator pretty soon, so I've added this as a high priority issue

**Comment by adamretter** [comment]
@clairedriver I have fixed that for you here - https://github.com/digital-preservation/csv-validator/issues/331
