### ISSUE TITLE
Publish a release candidate for 2.13

### ISSUE THREAD

**Issue by iggy-da** [digital-preservation/csv-validator#375]
Hi, could I please request an RC release following the Scala 2.13 upgrade? That is, if the [official release](https://github.com/digital-preservation/csv-validator/pull/155#issuecomment-1074961572) still needs more time. We are depending on `csv-validator` in a part of our Scala codebase, and it's preventing us from upgrading that code to a more recent Scala version. Thank you!

**Comment by iggy-da** [comment]
The release would still be very much appreciated.

@luketebbs @DavidUnderdown I saw that you rolled back `1.2.0-RC5` a few months ago - would you happen to know what happened there, is we'd have to watch out for if we would roll our own release for the time being?

**Comment by OliverHannan** [comment]
Hello @iggy-da. Thanks for raising the issue again. 

I understand the roll back was because we don't have dedicated developers to work on the product. Unfortunately that's still the case.

**Comment by ksclarke** [comment]
So it's fair to say this project is no longer under active development?

**Comment by sparkhi** [comment]
As there is a newer release already available, closing this issue.
