### ISSUE TITLE
if a single line comment is not terminated by new line at end of file, schema error is generated

### ISSUE THREAD

**Issue by DavidUnderdown** [digital-preservation/csv-validator#42]
If you wish to comment on the final Column Validation Expression of a schema, and use a single line comment (begun with //), and do not add a final newline character to terminate the comment, a schema error is generated.

**Comment by adamretter** [comment]
@DavidUnderdown I am not sure I follow the the issue that you are having here when you reopened this. Could you please provide a small example of the commenting issue that you are still experiencing?

**Comment by DavidUnderdown** [comment]
I'd mised this sorry.  I think we discussed this in some other context, and you pointed out that the spec specifically disallows asterisks in multiline comments.  Will re-close
