### ISSUE TITLE
Invalid release of 1.3.0

### ISSUE THREAD

**Issue by adamretter** [digital-preservation/csv-validator#475]
It seems that the 1.3.0 release was not done correctly by using the release plugin.

The Git version history does not reflect the changes that have been made - for example, after the release it still shows: `<version>1.2-SNAPSHOT</version>`

**Comment by steve-daly** [comment]
Hi @adamretter where are you seeing the mention of 1.2-SNAPSHOT?

**Comment by sparkhi** [comment]
I think we can close this issue.
