### ISSUE TITLE
Validating PAT_MRN_ID Across Three CSV Files

### ISSUE THREAD

**Issue by megin1989** [digital-preservation/csv-validator#501]
I have three CSV files: Screening, QeAdmin, and Demographics.

I need to validate that every PAT_MRN_ID in the Screening CSV matches the PAT_MRN_ID in both the QeAdmin and Demographics CSVs for the corresponding FACILITY_ID.

Additionally, how can I perform this validation across all three files?

**Comment by DavidUnderdown** [comment]
The validator can only operate on a single file at a time.

You could possibly achieve what you're after by calling the validator from another programme (eg Python) and having template CSVS files in which you inserted the relevant FACILITY_ID from one file as you validate the others, but this is beyond the scope of what the validator was designed to do.
