### ISSUE TITLE
csv val says csv val bat files etc 'are not listed in the metadata.'

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/csv-validator#503]
Hello, a  user  (who I'll invite onto this issue) emailed in saying that they're getting the error message ‘:   integrityCheck("") fails for line: 6, column: URI, files: ", running-csv-validator.txt, csv-validator-cmd.bat, csv-validator-gui.bat, csv-validator-cmd, LICENSE, csv-validator-ui-1.3.0.jar, csv-validator-gui, csv-validator-cmd-1.3.0.jar" are not listed in the metadata’ 

I was able to replicate this in csv val with jre on my IN machine:

![image](https://github.com/digital-preservation/csv-validator/assets/46964067/a3a11657-9be0-4136-8d56-0991df363a5b)

Odd, and intermittent- the files are defo not visible in the folder.

**Comment by sparkhi** [comment]
Can we have some more details and a few confirmations please
1) I assume this is on Windows, as "bundled JRE" is mentioned 
2) Can we please find out how the user has run it, one of the following  
-  double clicking the bat file, 
-  right click -> run 
-  ran the ba file from command prompt
3) If file path substitution is used, what values are used 

----- 
To me, it appears as if the files it is trying to look for are the ones which belong to the CSV validator rather than the data that they may want to validate?

**Comment by Lucy-Bonner** [comment]
Hi, I'm the user who is experiencing the message.

Yes, I'm using Windows, I'm not running any file substitution paths and I am running CSV validator via the bat file.

**Comment by sparkhi** [comment]
@kathaurielle could you please send to me the data you used for testing, either in email or here.
Thank you

**Comment by kathaurielle** [comment]
Just emailed you  SP, thank you.

**Comment by sparkhi** [comment]
I have managed to replicate it. I'll investigate further, however, unfortunately, I cannot give any timeline at this moment. 
Thanks

**Comment by kathaurielle** [comment]
Thank you SP, that is reassuring, although sorry it's more work for you. @Lucy-Bonner , if you need any help with this, let me know., as unfortunately the glitch will persist until fixed.

**Comment by sparkhi** [comment]
@kathaurielle and @Lucy-Bonner 
The error is stemming from the `integrityCheck` option. In the schema file, when defining the integrity check, the second parameter is the folder relative to where the CSV file resides. (if nothing is mentioned, we use "content" as a default) 

In your case, the data whose integrity needs to be checked is inside a folder called `Mayu` from the relative path of the CSV file. 

If you change line 31 to be `URI: fileExists integrityCheck("","Mayu","includeFolder")` that should look for only the files that are part of your data and the unnecessary error will go away. 

Hope this helps,
Many thanks.
