### ISSUE TITLE
Improve performance of checksum expressions

### ISSUE THREAD

**Issue by adamretter** [digital-preservation/csv-validator#55]
The National Archives have reported that when validating large CSV files where a row or rows reference files (and those files are large) and the Schema includes a `checksum` expression. The validation process can be quite slow.

Inside the validator each row is validated sequentially. If a row is slow to validate for example due to a checksum operation, it slows down the entire validation process. Some sort of multi-threading should be introduced to allow multiple checksums to be calculated in parallel, or even better perhaps to be able to perform out-of-order concurrent row validation.

**Comment by DavidUnderdown** [comment]
Don't think this was included in 1.1 in the end, unless @adamretter can confirm otherwise, so moved to 2.0 milestone for time being.

**Comment by adamretter** [comment]
@DavidUnderdown Pretty sure that we cracked that here https://github.com/digital-preservation/csv-validator/commit/947b7f41ddca5206e077475b7421c1833a2f1f58

**Comment by DavidUnderdown** [comment]
Close per Adam above, though may raise a new one for the multi-threading aspects which I don't think we did take forward.
