### ISSUE TITLE
Multiline comments fail if * is used anywhere other than opening or closing comment markers

### ISSUE THREAD

**Issue by DavidUnderdown** [digital-preservation/csv-validator#61]
Since Release 1.0 if you use an asterisk within a multiline comment other than in the open or close comment marker you get either:

[3.1] failure: Invalid column definition

/**-----------

If the asterisk immediately follows the open comment marker, or an apparently infinite hang if used elsewhere within the multiline comment.  This may be related to commit 8da45dc97fcd28c92f0c01d7589ea2b7a2de9503 which closed issue #42

**Comment by adamretter** [comment]
Asterisks are not permitted within multiline comments. This is defined in the CSV Schema 1.0. See http://digital-preservation.github.io/csv-schema/csv-schema-1.0.html#comments

Perhaps a feature request for CSV Schema 1.1? If so please file against the CSV Schema repository

**Comment by DavidUnderdown** [comment]
In itself that's fine, but I don't think the indefinite hang referred to in the second part of the issue is good.  It should return the Invalid column definition too

**Comment by DavidUnderdown** [comment]
Retested on latest version, and the hang has gone, so I'll close this now.
