### ISSUE TITLE
Create "identical" test

### ISSUE THREAD

**Issue by DavidUnderdown** [digital-preservation/csv-validator#67]
Some data should be the same in every row, in the standard TNA use case, this would be (for example) batch_code.  It differs from batch to batch so cannot use an "is" test without updating schema for every batch, but we do know it should not change within the metadata received for a single batch.  This is in a sense the converse of the "unique" test.

**Comment by adamretter** [comment]
Can you provide an example please?

**Comment by DavidUnderdown** [comment]
likely case is for batch_code.  Each batch has a different batch code, so while you can do something like regex("^WO95Y14B[0-9]$") to ensure the batch_code is of the correct form, there is no way of checking currently that the value is consistent within in a batch, short of changing the schema for each batch.

We've recently had the case where we had rejected images from a batch, and when these were resupplied in a later batch, the supplier left the original batch_code in the csv file in those lines relating to the resubmitted images, while material in the same batch that was being supplied for the first time had the batch_code for that actual  batch eg

lines with 

WO95Y14B012
WO95Y14B012
WO95Y14B012
WO95Y14B002
WO95Y14B012

**Comment by valydia** [comment]
It has been implemented in the [PR #86] (https://github.com/digital-preservation/csv-validator/pull/86).

**Comment by DavidUnderdown** [comment]
Closed with 1.1 release, commit 104ee5e
