### ISSUE TITLE
Enable checksum validation for files within ZIPs and similar compressed folders

### ISSUE THREAD

**Issue by DavidUnderdown** [digital-preservation/csv-validator#68]
DROID can read inside ZIPs and other containers and produce checksums for the individual files inside the ZIP.  When CSV Validator attempts to process a DROID csv file it then cannot verify the checksums for the individual files, producing a "NO CHECKSUM" message.

**Comment by alexgreenDP** [comment]
Decision made that this is out of scope for the CSV validator.
