### ISSUE TITLE
using range(1,*) within an if statement produces error

### ISSUE THREAD

**Issue by DavidUnderdown** [digital-preservation/csv-validator#69]
Get Schema error

[8.167] failure: string matching regex `-?[0-9]+(\.[0-9]+)?' expected but `*' found

**Comment by adamretter** [comment]
In CSV Schema 1.0, the range expression does not support wild-cards. Perhaps you are thinking of the length expression? http://digital-preservation.github.io/csv-schema/csv-schema-1.0.html#range-expressions

It could be easily added in a CSV Schema 1.1 if desirable? If so I can relabel this as a feature-request...

**Comment by DavidUnderdown** [comment]
It would seem logical

**Comment by adamretter** [comment]
Can you create a feature request against the CSV-Schema project please?

**Comment by valydia** [comment]
It has now been implemented in the [PR #85](https://github.com/digital-preservation/csv-validator/pull/85).

**Comment by DavidUnderdown** [comment]
Closed by release 1.1, commit 104ee5e
