### ISSUE TITLE
FailFast reports PASS even if there are warnings

### ISSUE THREAD

**Issue by DavidUnderdown** [digital-preservation/csv-validator#70]
FailFast is desired not to stop on warnings, but is actually suppressing them altogether, reporting PASS even if running the same validation without the FailFast switch does produce warnings.

**Comment by adamretter** [comment]
So, is this a feature request that the FailFast mode should also output the warnings?

**Comment by DavidUnderdown** [comment]
No I don't think so, there is no reason FailFast shouldn't output the warnings at the end.  It is misleading that it produces a PASS result just because there have been no errors.  It should produce exactly the same output as running without FailFast with the exception that it stops at the first error.

**Comment by adamretter** [comment]
I think we are saying the same thing in different ways!

If I understand, then you want FailFast to:

1. Output any warning messages as it processes the CSV file.
2. Stop on the first error it encounters (i.e. a non-warning)
3. Output the details of the error that caused it to stop.

Correct?

**Comment by DavidUnderdown** [comment]
Yes, but I see it as a bug in the original implementation (perhaps of warnings rather than failfast), rather than a feature request

**Comment by adamretter** [comment]
Okay I will take a look...
