### ISSUE TITLE
fails to parse over-complex path

### ISSUE THREAD

**Issue by navtis** [digital-preservation/csv-validator#80]
/mnt/imf/RW_32/content/EA-TNA1108.www.publicappts-vacs.gov.uk~%28sstth555zlg2npizrrzqgo45%29~Default.aspx/EA-TNA1108.www.publicappts-vacs.gov.uk~%28sstth555zlg2npizrrzqgo45%29~Default.aspx-20081211214944-00000.arc.gz

returns 'fileExists fails' , although file is present

**Comment by adamretter** [comment]
I guess it's an encoding issue e.g. `%28`. What is the name of the file on the filesystem, does it have %28 etc in it's filename, or does it have the unencoded characters?

**Comment by navtis** [comment]
%28 (the path above is a copy-and-paste from 'ls')

**Comment by adamretter** [comment]
Okay so, I suspect a double encoding issue. I do wonder know if the %28 should be on the filesystem; Regardless it doesn't really matter the csv-validator should be able to cope with any valid filesystem filename. I will try and take a look...

**Comment by DavidUnderdown** [comment]
fixed in tag 1.0.1 and subsequent (commit dbf59d1)
